export const routes = {
  dashboard: '/',
  plants: '/plants',
  ailments: '/ailments',
  wellness: '/wellness',
  preparations: '/preparations',
  entheogenic: '/entheogens',
  'body-systems': '/body-systems',
  collections: '/collections',
  astrology: '/astrology/signs',
  'astrology-planets': '/astrology/planets',
  'natal-chart': '/astrology/natal-chart',
  'planetary-timing': '/astrology/planetary-timing',
  hmbs: '/hmbs',
  seasonal: '/seasonal',
  doctrine: '/doctrine',
  journal: '/journal',
  crossref: '/crossref',
} as const
